# https://docs.codecov.io/docs/commit-status
coverage:
  status:
    # only measure diff changes, not unexpected project changes from flakiness
    project:
      default: off
      ui:
        flags: ui
        informational: true
    patch:
      default:
        # https://docs.codecov.io/docs/commit-status#section-informational
        informational: true
      ui:
        flags: ui
        informational: true
    # https://docs.codecov.io/docs/commit-status#section-changes-status
    # TODO: enable after eliminating current unexpected coverage changes?
    changes: off

# https://docs.codecov.io/docs/codecov-yaml#section-default-yaml
# TODO: experiment with changing these values?
# parsers:
#   gcov:
#     branch_detection:
#       conditional: yes
#       loop: yes
#       method: no
#       macro: no

# https://docs.codecov.io/docs/pull-request-comments
comment: false

# https://docs.codecov.io/docs/flags
# TODO: split out test coverage for API, SDK, website?
flags:
  ui:
    paths:
      - ui-v2
